### ISSUE TITLE
我fork了一份放到gitbook上便于查看

### ISSUE THREAD

**Issue by gafish** [liunian/webpack-doc#15]
你好，看到了你们的中文文档整理的非常好，但没有在线版本可看，为了便于在线浏览，我fork了一份到我的github，然后导到了gitbook中在线查阅，地址：https://gafish.gitbooks.io/webpack/content/ 
纯属便于个人查阅，但还是想征求下原作者的意见，如有冒犯，我将立即撤下。

**Comment by liunian** [comment]
@gafish 辉哥随意即可，我这只是之前个人学习用的，都木有完成
